### ISSUE TITLE
Bug in unpack_unravel

### ISSUE THREAD

**Issue by maharjun** [gngdb/pytorch-minimize#1]
* PyTorch Minimize version:
* Python version:
* Operating System:

### Description

line 79 of optim.py should be i += j (not i = j). the reason is pretty clear I hope.
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by gngdb** [comment]
Thanks, I fixed it. I had a test that would have caught this but it was commented out in the class and as long as there were only two parameter tensors it'd never fail. Unfortunately, all my tests run with logistic regression with two parameter tensors.

Added [this test](https://github.com/gngdb/pytorch-minimize/blob/master/tests/test_unpack_unravel.py) that catches it.
